# PURL configuration for http://purl.obolibrary.org/obo/pcl

idspace: PCL
base_url: /obo/pcl

products:
- pcl.owl: https://raw.githubusercontent.com/obophenotype/provisional_cell_ontology/master/pcl.owl
- pcl.obo: https://raw.githubusercontent.com/obophenotype/provisional_cell_ontology/master/pcl.obo
- pcl.json: https://raw.githubusercontent.com/obophenotype/provisional_cell_ontology/master/pcl.json

term_browser: ols
example_terms:
- PCL_0011124

entries:

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/obophenotype/provisional_cell_ontology/v
  tests:
    - from: /releases/2022-01-24/
      to: https://raw.githubusercontent.com/obophenotype/provisional_cell_ontology/v2022-01-24/

- prefix: /tracker/
  replacement: https://github.com/obophenotype/provisional_cell_ontology/issues

- prefix: /about/
  replacement: https://github.com/obophenotype/provisional_cell_ontology#readme

- exact: /bds/kg
  replacement: http://ec2-3-143-113-50.us-east-2.compute.amazonaws.com:7472/browser

- prefix: /bds/kg/
  replacement: http://ec2-3-143-113-50.us-east-2.compute.amazonaws.com:7472/browser
  
- prefix: /bds/api/
  replacement: http://ec2-3-143-113-50.us-east-2.compute.amazonaws.com:8484/bds/

## generic fall-through, serve direct from github by default
- prefix: /
  replacement: https://raw.githubusercontent.com/obophenotype/provisional_cell_ontology/master/
